### PR TITLE
[minor_change] try login for pwd set

### LINKED ISSUE #984: Unable to set local user description using aci_local_user
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.5.2
```

### APIC version and APIC Platform

* V 5.2(3g) on-prem.

### Affected Resource(s)

* aci_local_user

### Terraform Configuration Files

1. I create a user with:

   ```hcl
   resource "aci_local_user" "test_user" {
     name                = "test_user"
     description         = ""
     pwd                 = "super_secret123#!"
     pwd_update_required = "yes"

     # ignore password changes
     lifecycle {
       ignore_changes = [pwd, pwd_update_required]
     }
   }
   ```

   And I can apply it fine

   ```text
   Terraform will perform the following actions:
   
     # aci_local_user.test_user will be created
     + resource "aci_local_user" "test_user" {
         + account_status      = (known after apply)
         + annotation          = "orchestrator:terraform"
         + cert_attribute      = (known after apply)
         + clear_pwd_history   = (known after apply)
         + description         = (known after apply)
         + email               = (known after apply)
         + expiration          = (known after apply)
         + expires             = (known after apply)
         + first_name          = (known after apply)
         + id                  = (known after apply)
         + last_name           = (known after apply)
         + name                = "test_user"
         + name_alias          = (known after apply)
         + otpenable           = (known after apply)
         + otpkey              = (known after apply)
         + phone               = (known after apply)
         + pwd                 = "super_secret123#!"
         + pwd_life_time       = (known after apply)
         + pwd_update_required = "yes"
         + rbac_string         = (known after apply)
         + unix_user_id        = (known after apply)
       }
   
   Plan: 1 to add, 0 to change, 0 to destroy.
   
   Do you want to perform these actions?
     Terraform will perform the actions described above.
     Only 'yes' will be accepted to approve.
   
     Enter a value: yes
   
   aci_local_user.test_user: Creating...
   aci_local_user.test_user: Creation complete after 0s [id=uni/userext/user-test_user]
   
   Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
   ```

2. Login with that local user and set a new password.
3. Add description and run `terrafrom apply` again.

   ```hcl
   resource "aci_local_user" "test_user" {
     name                = "test_user"
     description         = "Short user description"
     pwd                 = "super_secret123#!"
     pwd_update_required = "yes"
   
     # ignore password changes
     lifecycle {
       ignore_changes = [pwd, pwd_update_required]
     }
   }
   ```

   But I get this:

   ```text
   Terraform will perform the following actions:
   
     # aci_local_user.test_user will be updated in-place
     ~ resource "aci_local_user" "test_user" {
         + description         = "Short user description"
           id                  = "uni/userext/user-test_user"
           name                = "test_user"
           # (11 unchanged attributes hidden)
       }
   
   Plan: 0 to add, 1 to change, 0 to destroy.
   
   Do you want to perform these actions?
     Terraform will perform the actions described above.
     Only 'yes' will be accepted to approve.
   
     Enter a value: yes
   
   aci_local_user.test_user: Modifying... [id=uni/userext/user-test_user]
   ╷
   │ Error: Password history check: user test_user should not use previous 5 passwords
   │ 
   │   with aci_local_user.test_user,
   │   on aci_local_user.tf line 33, in resource "aci_local_user" "test_user":
   │   33: resource "aci_local_user" "test_user" {
   ```

### Expected Behavior

I want to set a user description with terrafrom ignoring password changes.

### Actual Behavior

```text
Error: Password history check: user test_user should not use previous 5 passwords
```

### Steps to Reproduce

1. Create a local user without a description using `aci_local_user` resource.
2. `terraform apply`
3. Login with that user and update the password.
4. Add a description.
5. Run `terraform apply` again.

### PR DESCRIPTION
**Pull request by akinross**
fixes #984

### CODE REVIEW

File: aci/resource_aci_aaauser.go [hunk 1]
```diff
@@ -203,6 +231,11 @@ func setLocalUserAttributes(aaaUser *models.LocalUser, d *schema.ResourceData) (
 	d.Set("pwd_update_required", aaaUserMap["pwdUpdateRequired"])
 	d.Set("rbac_string", aaaUserMap["rbacString"])
 	d.Set("unix_user_id", aaaUserMap["unixUserId"])
+
+	if loginSuccess || d.HasChange("pwd") {
```
[the remark this answers is not in the document]
Comment (akinross) [reply aci/resource_aci_aaauser.go]: tested without and is redundant, so removed the hasChange

File: aci/resource_aci_aaauser.go [hunk 2]
```diff
@@ -203,6 +231,11 @@ func setLocalUserAttributes(aaaUser *models.LocalUser, d *schema.ResourceData) (
...
+		d.Set("pwd", d.Get("pwd").(string))
```
[the remark this answers is not in the document]
Comment (akinross) [reply aci/resource_aci_aaauser.go:236]: correct, the additional check provided same result but redundant so removed

[the remark this answers is not in the document]
Comment (lhercot) [reply aci/resource_aci_aaauser.go:236]: Still there. Check apply, manual change in APIC and re-apply.

File: aci/resource_aci_aaauser.go [hunk 3]
```diff
@@ -157,6 +157,35 @@ func resourceAciLocalUser() *schema.Resource {
...
+	req, err := aciClient.MakeRestRequestRaw("POST", "/api/aaaLogin.json", []byte(fmt.Sprintf(authPayload, d.Get("name").(string), d.Get("pwd").(string))), false)
+	if err != nil {
+		log.Printf("[DEBUG] Creation of authentication request failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
+		return false
+	}
+
+	_, resp, _ := aciClient.Do(req)
+
+	if resp.StatusCode != 200 {
+		log.Printf("[DEBUG] Authentication failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
```
Comment (lhercot) [inline aci/resource_aci_aaauser.go:181]: Do we want to log the password?

File: aci/resource_aci_aaauser.go [hunk 4]
```diff
@@ -157,6 +157,35 @@ func resourceAciLocalUser() *schema.Resource {
...
+			"attributes" : {
+				"name" : "%s",
+				"pwd" : "%s"
+			}
+		}
+	}`
+
+	req, err := aciClient.MakeRestRequestRaw("POST", "/api/aaaLogin.json", []byte(fmt.Sprintf(authPayload, d.Get("name").(string), d.Get("pwd").(string))), false)
+	if err != nil {
+		log.Printf("[DEBUG] Creation of authentication request failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
```
Comment (lhercot) [inline aci/resource_aci_aaauser.go:174]: Do we want to log the password?

File: aci/resource_aci_aaauser.go [hunk 5]
```diff
@@ -157,6 +157,35 @@ func resourceAciLocalUser() *schema.Resource {
...
+	}
+
+	_, resp, _ := aciClient.Do(req)
+
+	if resp.StatusCode != 200 {
+		log.Printf("[DEBUG] Authentication failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
+		return false
+	}
+
+	log.Printf("[DEBUG] Authentication succceeded for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
```
Comment (lhercot) [inline aci/resource_aci_aaauser.go:185]: Do we want to log the password?

**Review by lhercot — CHANGES_REQUESTED** [review]

File: aci/resource_aci_aaauser.go (hunk 4 above)
Comment (akinross) [reply aci/resource_aci_aaauser.go:174]: no will remove

File: aci/resource_aci_aaauser.go (hunk 5 above)
Comment (akinross) [reply aci/resource_aci_aaauser.go:185]: no will remove

File: aci/resource_aci_aaauser.go [hunk 6]
```diff
@@ -157,6 +157,35 @@ func resourceAciLocalUser() *schema.Resource {
...
+
+	authPayload := `{
+		"aaaUser" : {
+			"attributes" : {
+				"name" : "%s",
+				"pwd" : "%s"
+			}
+		}
+	}`
+
```
[the remark this answers is not in the document]
Comment (akinross) [reply aci/resource_aci_aaauser.go:171]: can't access the skipLoggingPayload of client since it is private to the package, would need to change in aci-go-client?

**Review by anvitha-jain — DISMISSED** [review]
LGTM

File: aci/resource_aci_aaauser.go [hunk 7]
```diff
@@ -276,8 +314,13 @@ func resourceAciLocalUserCreate(ctx context.Context, d *schema.ResourceData, m i
 	if Phone, ok := d.GetOk("phone"); ok {
 		aaaUserAttr.Phone = Phone.(string)
 	}
-	if Pwd, ok := d.GetOk("pwd"); ok {
-		aaaUserAttr.Pwd = Pwd.(string)
+	if pwd, ok := d.GetOk("pwd"); ok {
+		loginSuccess := tryLogin(d, aciClient)
+		if !loginSuccess {
+			log.Printf("[DEBUG] SETTING SKIP")
```
Comment (lhercot) [inline aci/resource_aci_aaauser.go:320]: Do we need this log?

**Review by lhercot — CHANGES_REQUESTED** [review]

File: aci/resource_aci_aaauser.go (hunk 7 above)
Comment (akinross) [reply aci/resource_aci_aaauser.go:320]: no thought i removed all logs
