### PR TITLE
[bugfix] default annotation setting and annotation setting for object…

### LINKED ISSUE #1074: aci_rest_managed - inconsistently sets annotation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V 6.0.2 and on-prem

### Affected Resource(s)

* aci_rest_managed

### Terraform Configuration Files

```hcl
resource "aci_rest_managed" "bgp_instance" {
      class_name = "bgpInstPol"
      content    = {
         "annoation" = "BLAH"
          "descr"     = ""
          "name"      = "default"
          "nameAlias" = ""
          "ownerKey"  = ""
          "ownerTag"  = ""
          "userdom"   = "all"
        } 
      dn         = "uni/fabric/bgpInstP-default"
      id         = "uni/fabric/bgpInstP-default"
    }
```

### Debug Output

```
  ~ resource "aci_rest_managed" "bgp_instance" {
      ~ content    = {
          + "annotation" = "BLAH"
            # (6 unchanged elements hidden)
        }
        id         = "uni/fabric/bgpInstP-default"
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
````
### Expected Behavior

Annotation should be applied with the terraform:orchestration tag consistently to inform users that objects are being managed by IaC.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #1086: aci_rest_managed - in many instances sets annotation but on re-apply says that it needs to be updated
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V 6.0.2 and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* aci_rest_managed
*  aci_fabric_node_control
* aci_l3_interface_policy
* aci_vlan_pool

### Terraform Configuration Files

```hcl
resource "aci_rest_managed" "fabric_wide_settings_5_2_3" {
    class_name = "infraSetPol"
    content    = {
        "annotation" = "orchestrator:terraform"
        "dampFactor"                     = "1"
        "descr"                          = ""
        "disableEpDampening"             = "no"
        "domainValidation"               = "yes"
        "enableMoStreaming"              = "yes"
        "enableRemoteLeafDirect"         = "yes"
        "enforceSubnetCheck"             = "no"
        "leafOpflexpAuthenticateClients" = "yes"
        "leafOpflexpUseSsl"              = "yes"
        "name"                           = "default"
        "nameAlias"                      = ""
        "opflexpAuthenticateClients"     = "yes"
        "opflexpSslProtocols"            = "TLSv1.2"
        "opflexpUseSsl"                  = "yes"
        "ownerKey"                       = ""
        "ownerTag"                       = ""
        "policySyncNodeBringup"          = "yes"
        "reallocateGipo"                 = "no"
        "restrictInfraVLANTraffic"       = "no"
        "unicastXrEpLearnDisable"        = "yes"
        "userdom"                        = "all"
        "validateOverlappingVlans"       = "no"
    }
    dn         = "uni/infra/settings"
    id         = "uni/infra/settings"
}

```

### Steps to Reproduce

1. `terraform apply`

on re-apply even though the api has the value of the annotation, the annotation object is missing from the state file, and it believes it needs to be updated.

```hcl
  # module.system_settings["default"].aci_rest_managed.fabric_wide_settings_5_2_3["default"] will be updated in-place
  ~ resource "aci_rest_managed" "fabric_wide_settings_5_2_3" {
      ~ content    = {
          + "annotation"                     = "orchestrator:terraform"
            # (22 unchanged elements hidden)
        }
        id         = "uni/infra/settings"
        # (2 unchanged attributes hidden)
    }
```

A few examples are:
infraSetPol
latencyPtpMode
fabricProtPol
vzOOBBrCP
mgmtInstP

I may have more in tenant policies and route-maps.  But I need to do further testing there.

If I try to add annotation to infraSHPortS I get the following error

```hcl
│ Error: Admin implicit props cannot be modified, class=infraSHPortS, prop=creator
│ 
│   with module.switch["default"].aci_rest_managed.spine_interface_selectors["102-Eth1/1"],
│   on ../../../terraform-aci-switch/switch_profiles.tf line 249, in resource "aci_rest_managed" "spine_interface_selectors":
│  249: resource "aci_rest_managed" "spine_interface_selectors" {

```

If I try to add annotation to syslogGroup I get the following error:
```hcl
╷
│ Error: Admin implicit props cannot be modified, class=syslogGroup, prop=remoteDestCount
│ 
│   with module.admin["default"].aci_rest_managed.syslog_destination_groups["default"],
│   on ../../../terraform-aci-admin/external_data_collectors.tf line 166, in resource "aci_rest_managed" "syslog_destination_groups":
│  166: resource "aci_rest_managed" "syslog_destination_groups" {
│ 
```
Additional challenges with some more with trying to utilize annotation
```hcl
╷
│ Error: Admin implicit props cannot be modified, class=dnsProfile, prop=epgDn
│ 
│   with module.fabric["default"].aci_rest_managed.dns_profiles["default"],
│   on ../../../terraform-aci-fabric/policies-global.tf line 10, in resource "aci_rest_managed" "dns_profiles":
│   10: resource "aci_rest_managed" "dns_profiles" {
│ 
╵
│ Error: Admin implicit props cannot be modified, class=snmpTrapDest, prop=epgDn
│ 
│   with module.fabric["default"].aci_rest_managed.snmp_trap_destinations["default:10.101.128.25"],
│   on ../../../terraform-aci-fabric/policies-pod.tf line 279, in resource "aci_rest_managed" "snmp_trap_destinations":
│  279: resource "aci_rest_managed" "snmp_trap_destinations" {
│ 
╵
```

The following are ignoring annotation all together.
snmpSrc
snmpTrapFwdServerP
snmpGroup
snmpPol
datetimeFormat
datetimePol
fabricPodPGrp
fabricPodP
fabricPodS
syslogRemoteDest
syslogSrc

With aci_fabric_node_control ignores annotation.
aci_l3_interface_policy ignores annotation.
aci_vlan_pool isn't by default setting annotation.

In function it is working but annotation is not being added to the state, so it believes it needs to re-apply each time.

On a Side note, outside of the provider and with the GUI, it seems to be inconsistent when the Tag is added to the object or not.

i.e.
BGP Route Reflector and COOP Group show it.
APIC Connectivity Preference, Fabric-Wide Settings, Global AES, ISIS Policy, Port Tracking, PTP and Latency, qosInstPol, infraSpAccPortGrp, Admin > AAA > Authentication Default Settings/Security Default Settings,  do not.
Would be nice for the UI to be consistent.

### References

* #0000

### PR DESCRIPTION
**Pull request by akinross**
… and children in aci_rest_managed

fixes #1086 
fixes #1074

### CODE REVIEW

File: aci/resource_aci_rest_managed.go [hunk 1]
```diff
@@ -120,9 +120,13 @@ func getAciRestManaged(d *schema.ResourceData, c *container.Container, expectObj
...
-		if !containsString(IgnoreAttr, attr) {
-			newContent[attr] = value.(string)
+		if _, ok := contentStrMap[attr]; ok {
+			if !containsString(IgnoreAttr, attr) {
+				newContent[attr] = value.(string)
+			}
+		}
+		if attr == "annotation" {
+			d.Set("annotation", value.(string))
 		}
```
Comment (sajagana) [inline aci/resource_aci_rest_managed.go:130]: Can we use else instead using one more if condition?

File: aci/resource_aci_rest_managed.go [hunk 2]
```diff
@@ -119,9 +119,16 @@ func getAciRestManaged(d *schema.ResourceData, c *container.Container, expectObj
...
+	if _, ok := contentStrMap["annotation"]; ok {
+		setContentAnnotation = true
+	}
+
 	for attr, value := range restContent {
 		// Ignore certain attributes
-		if !containsString(IgnoreAttr, attr) {
+		if attr == "annotation" && setContentAnnotation {
+			newContent[attr] = value.(string)
+		} else if attr != "annotation" && !containsString(IgnoreAttr, attr) {
```
Comment (anvitha-jain) [inline aci/resource_aci_rest_managed.go:131]: any particular reason this is else if and not else ?

**Review by anvitha-jain — CHANGES_REQUESTED** [review]

File: aci/resource_aci_rest_managed.go (hunk 2 above)
Comment (akinross) [reply aci/resource_aci_rest_managed.go:131]: Yes because it needs to be added only when a certain condition is met. In this case that would be the following:

1. `attr != "annotation"` - because in the if condition setContentAnnotation (used to determine if annotation is set in the content input map) is set to False the else statement could have scenario where `attr == "annotation"` thus we need to check again
2. !containsString(IgnoreAttr, attr) - because certain attributes should not be set in content, if else it would add all attributes and the conditional would not be needed

**Review by shrsr — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]

**Review by gmicol — APPROVED** [review]
LGTM!

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by lhercot — APPROVED** [review]
LGTM
