### PR TITLE
[minor_change] Migration of aci_rest_managed into plugin framework

### LINKED ISSUE #1108: aci_rest_managed child panic
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.6
on windows_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.10.1

Also tested with 1.6.0-beta3 - same result

### APIC version and APIC Platform

* Version 6.0(2h) ACI_SIM,  not tested on physical

### Affected Resource(s)

* aci_rest_managed

### Terraform Configuration Files

variable pod1_tep {
  type        = string
  default     = "10.0.0.0/16"
  description = "Tep pool ip for pod 1"
}
variable pod1_ext_tep {
  type        = string
  default     = "10.2.0.0/24"
  description = "external tep pool ip for pod 1"
}

resource "aci_rest_managed" "pod1_tep" {
  dn         = "uni/controller/setuppol/setupp-1"
  class_name = "fabricSetupP"
  content = {
    tepPool  = var.pod1_tep
    podId = 1
    annotation = "orchestrator:terraform"
  }
  child {
    rn         = "extrtpodsubnet-[${var.pod1_ext_tep}]"
    class_name = "fabricExtRoutablePodSubnet"
    content = {
      dn = "uni/controller/setuppol/setupp-1/extrtpodsubnet-[${var.pod1_ext_tep}]"
      pool = var.pod1_ext_tep
      annotation = "orchestrator:terraform"
    }
  }
}

### Panic Output

aci_rest_managed.pod1_tep: Modifying... [id=uni/controller/setuppol/setupp-1]
╷
│ Error: Plugin did not respond
│
│   with aci_rest_managed.pod1_tep,
│   on pod.tf line 1, in resource "aci_rest_managed" "pod1_tep":
│    1: resource "aci_rest_managed" "pod1_tep" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aci_v2.10.1.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 15 [running]:
github.com/terraform-providers/terraform-provider-aci/aci.getAciRestManaged(0xc000555fe0?, 0x1d1cae0?, 0x1)
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:157 +0x102a
github.com/terraform-providers/terraform-provider-aci/aci.resourceAciRestManagedReadHelper({0x1d6522d?, 0x20?}, 0xc0008cd800, {0x1d1cae0, 0xc00050a540}, 0x1)
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:190 +0x1d1
github.com/terraform-providers/terraform-provider-aci/aci.resourceAciRestManagedUpdate({0x1f05d68, 0xc0004d0a20}, 0xc0008cd800, {0x1d1cae0, 0xc00050a540})
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:220 +0x265
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0000cbdc0, {0x1f05da0, 0xc00094cc90}, 0xd?, {0x1d1cae0, 0xc00050a540})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000cbdc0, {0x1f05da0, 0xc00094cc90}, 0xc0004d3790, 0xc0008cd680, {0x1d1cae0, 0xc00050a540})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000d2280, {0x1f05da0?, 0xc0006abc50?}, 0xc0004e2770)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1ce3c20?, 0xc0000d2280}, {0x1f05da0, 0xc0006abc50}, 0xc0004e2700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f6000, {0x1f08d60, 0xc0006a8000}, 0xc00058b440, 0xc00060c330, 0x26dea20, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000f6000, {0x1f08d60, 0xc0006a8000}, 0xc00058b440, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-aci_v2.10.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

Panic

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Resource run is able to run without the child block, to just create the pod

### References

* #0000

### PR DESCRIPTION
**Pull request by akinross**
fixes #1108

### CODE REVIEW

File: internal/provider/resource_aci_rest_managed.go [hunk 1]
```diff
@@ -0,0 +1,519 @@
...
+}
+
+func (r *AciRestManagedResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
+	resp.Schema = schema.Schema{
+		// This description is used by the documentation generator and the language server.
+		MarkdownDescription: "Manages ACI Model Objects via REST API calls. This resource can only manage a single API object and its direct children. It is able to read the state and therefore reconcile configuration drift.",
+		Attributes: map[string]schema.Attribute{
+			"id": schema.StringAttribute{
+				Computed:            true,
+				MarkdownDescription: "The distinquised name (DN) of the object.",
```
Comment (shrsr) [inline internal/provider/resource_aci_rest_managed.go:98]: The distinguished name

File: docs/resources/rest_managed.md [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+  content = {
+    interfacePref = "ooband"
+  }
+}
+```
+
+The configuration snippet below creates a Tenant object with a VRF as child with annotation overwrites.
+
+```terraform
+resource "aci_rest_managed" "example_tenant_with_child" {
```
Comment (shrsr) [inline docs/resources/rest_managed.md:48]: Shall we add another direct child to show that you can add more than one?

File: internal/provider/resource_aci_rest_managed.go [hunk 3]
```diff
@@ -0,0 +1,519 @@
...
+				PlanModifiers: []planmodifier.String{
+					stringplanmodifier.UseStateForUnknown(),
+				},
+				Default:             stringdefault.StaticString(globalAnnotation),
+				MarkdownDescription: `The annotation of the ACI object.`,
+			},
+		},
+		Blocks: map[string]schema.Block{
+			"child": schema.SetNestedBlock{
+				//Optional:            true,
```
Comment (shrsr) [inline internal/provider/resource_aci_rest_managed.go:140]: Why is this commented?

**Review by shrsr — CHANGES_REQUESTED** [review]

File: docs/resources/rest_managed.md (hunk 2 above)
Comment (akinross) [reply docs/resources/rest_managed.md:48]: discussed not needed

**Review by shrsr — DISMISSED** [review]
LGTM

**Review by sajagana — CHANGES_REQUESTED** [review]
The aci_rest_managed resource import and the data source output looks different and also if possible try to update the `dn` and `annotation` attribute values when we use the import command: `terraform import aci_rest_managed.example_tenant "uni/tn-EXAMPLE_TENANT"`

File: docs/data-sources/rest_managed.md [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+
+### Required ###
+
+* `dn` - (string) Distinguished Name of the object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
+
+### Read-Only ###
+
+* `class_name` - (string) Which class object is being created.
+* `id` - (string) The Distinguished Name of the object.
+* `annotation` - (string) Annotation for the class object that is being created. When annotation is provided in content this will take precedence.
```
Comment (samiib) [inline docs/data-sources/rest_managed.md:35]: Its not clear from the comment what will take precedence. Annotation in the content or this annotation attribute?

```suggestion
* `annotation` - (string) Annotation for the class object that is being created. When annotation is provided in the content it will take precedence over this annotation attribute.
```

File: internal/provider/resource_aci_rest_managed.go [hunk 5]
```diff
@@ -0,0 +1,518 @@
...
+		for _, child := range childState {
+			delete := true
+			for _, childIdentifier := range childIdentifiers {
+				if childIdentifier.Rn == child.Rn && childIdentifier.ClassName == child.ClassName {
+					delete = false
+					break
+				}
+			}
+			if delete {
+				// TODO check if this works
```
Comment (samiib) [inline internal/provider/resource_aci_rest_managed.go:459]: Can this TODO be removed now? I think changing the class or rn of child works as expected?
Pretty sure I added this here but may not have removed it.
```suggestion
```

**Review by samiib — CHANGES_REQUESTED** [review]

File: docs/data-sources/rest_managed.md (hunk 4 above)
Comment (akinross) [reply docs/data-sources/rest_managed.md:35]: changed but slightly different due to functionality change

File: internal/provider/resource_aci_rest_managed.go (hunk 5 above)
Comment (akinross) [reply internal/provider/resource_aci_rest_managed.go]: removed

**Review by anvitha-jain — APPROVED** [review]

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by samiib — CHANGES_REQUESTED** [review]

File: internal/provider/resource_aci_rest_managed.go [hunk 6]
```diff
@@ -0,0 +1,628 @@
...
+	if !req.Plan.Raw.IsNull() {
+		var planData *AciRestManagedResourceModel
+		resp.Diagnostics.Append(req.Plan.Get(ctx, &planData)...)
+
+		// modify the plan when annotation is not a property of class
+		if ContainsString(NoAnnotationClasses, planData.ClassName.ValueString()) {
+			planData.Annotation = basetypes.NewStringNull()
+		} else if !planData.Content.IsNull() && !planData.Content.IsUnknown() && planData.Content.Elements()["annotation"] != nil {
+			if !planData.Content.Elements()["annotation"].IsNull() {
+				resp.Diagnostics.AddError(
```
[the remark this answers is not in the document]
Comment (akinross) [reply internal/provider/resource_aci_rest_managed.go:94]: correct

File: docs/resources/rest_managed.md [hunk 7]
```diff
@@ -0,0 +1,120 @@
+---
+# Documentation generated by "gen/generator.go"; DO NOT EDIT.
```
[the remark this answers is not in the document]
Comment (akinross) [reply docs/resources/rest_managed.md:2]: It's not "generated" but copied from legacy docs, when go generate is run. Not sure if we want to auto-generate or ignore the deletion here. So kept in legacy docs for now and copy during generate. This way we should also see changes made in the diff

# Copied from legacy-docs, in order to make changes change this file in legacy-docs and execute `go generate` from the repository root.
# More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

File: docs/data-sources/rest_managed.md [hunk 8]
```diff
@@ -0,0 +1,41 @@
+---
+# Documentation generated by "gen/generator.go"; DO NOT EDIT.
```
[the remark this answers is not in the document]
Comment (akinross) [reply docs/data-sources/rest_managed.md:2]: same as above

File: docs/resources/rest_managed.md [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+}
+```
+
+## Schema ##
+
+### Required ###
+
+* `class_name` - (string) Which class object is being created.
+
+  !> Make sure there is no colon `:` in the classname
```
[the remark this answers is not in the document]
Comment (akinross) [reply docs/resources/rest_managed.md:72]: The correct example is already there, so does it make sense to add another? If  you feel it is more clear I can add

File: internal/provider/data_source_aci_rest_managed.go [hunk 10]
```diff
@@ -0,0 +1,210 @@
...
+				Computed:            true,
+				MarkdownDescription: "The distinguished name (DN) of the object.",
+			},
+			"dn": schema.StringAttribute{
+				Required:            true,
+				MarkdownDescription: "The distinguished name (DN) of the parent object. e.g. uni/tn-EXAMPLE_TENANT",
+			},
+			"class_name": schema.StringAttribute{
+				Computed:            true,
+				MarkdownDescription: "Which class object is being created. (Make sure there is no colon in the classname)",
```
[the remark this answers is not in the document]
Comment (akinross) [reply internal/provider/data_source_aci_rest_managed.go:52]: data source so computed and no input allowed so not needed.

File: internal/provider/resource_aci_rest_managed.go [hunk 11]
```diff
@@ -0,0 +1,722 @@
...
+				Required:            true,
+				MarkdownDescription: "Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.",
+				PlanModifiers: []planmodifier.String{
+					stringplanmodifier.UseStateForUnknown(),
+					stringplanmodifier.RequiresReplace(),
+				},
+			},
+			"class_name": schema.StringAttribute{
+				Required:            true,
+				MarkdownDescription: "Which class object is being created. (Make sure there is no colon in the classname)",
```
[the remark this answers is not in the document]
Comment (akinross) [reply internal/provider/resource_aci_rest_managed.go:128]: Not really used this Markdowndescription but will change for consistency

File: docs/resources/rest_managed.md (hunk 9 above)
[the remark this answers is not in the document]
Comment (samiib) [reply docs/resources/rest_managed.md:72]: No, all good. If the correct example is already there, should be okay.

**Review by samiib — APPROVED** [review]
LGTM

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by shrsr — APPROVED** [review]
LGTM

**Review by gmicol — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]

**Review by lhercot — APPROVED** [review]
LGTM
