### PR TITLE
[minor_change] Enable escaping of HTML characters in Payload.

### LINKED ISSUE #1181: Special characters being converted into unicode when used in Controller CLI Banner and Switch CLI Banner
### Terraform Version

Terraform v1.6.4

### APIC version and APIC Platform

4.2(7f) on prem

### Affected Resource(s)

Not sure

### Terraform Configuration Files

```
apic:
  fabric_policies:
    apic_conn_pref: ooband
    banners:
      apic_cli_banner: '<<< WARNING >>>  THE PROGRAMS AND DATA HELD ON THIS SYSTEM
        ARE THE PROPERTY OF, OR LICENCED BY, XXXXXXXX. IF THE COMPANY HAS NOT
        AUTHORISED YOUR ACCESS TO THIS SYSTEM YOU WILL COMMIT A CRIMINAL OFFENCE IF
        YOU DO NOT IMMEDIATELY DISCONNECT. UNAUTHORISED ACCESS IS STRICTLY FORBIDDEN
        AND IS A DISCIPLINARY OFFENCE.'
      switch_cli_banner: "<<< WARNING >>>  THE PROGRAMS AND DATA HELD ON THIS SYSTEM
        ARE THE PROPERTY OF, OR LICENCED BY, XXXXXXXX. IF THE COMPANY HAS NOT
        AUTHORISED YOUR ACCESS TO THIS SYSTEM YOU WILL COMMIT A CRIMINAL OFFENCE IF
        YOU DO NOT IMMEDIATELY DISCONNECT. UNAUTHORISED ACCESS IS STRICTLY FORBIDDEN
        AND IS A DISCIPLINARY OFFENCE."
```

### Debug Output

No debug, incorrect value pushed into APIC

### Panic Output

N/A

### Expected Behavior

The text in the input yaml files should be reflected in the APIC

### Actual Behavior

The following text is displayed instead

"\u003c\u003c\u003c WARNING \u003e\u003e\u003e  THE PROGRAMS AND DATA HELD ON THIS SYSTEM ARE THE PROPERTY OF, OR LICENCED BY"

### Steps to Reproduce

Seems to appear inside the plan file so the string conversion or handling must take place as part of the building the plan

### Important Factoids

No

### PR DESCRIPTION
**Pull request by anvitha-jain**
fix #1181 
This change enables escaping of HTML characters '<' and '>' when encoding the JSON payload.
- DoRestRequest() in utils.go accepts an additional boolean parameter escapeHtml by default it is true ('<' -> '\u003c')
- escapeHtml when set to false calls MakeRestRequestRaw(), which will retain the HTML charecters as is it '<' -> '<'

### CODE REVIEW

File: internal/provider/utils.go [hunk 1]
```diff
@@ -41,14 +42,19 @@ func CheckDn(ctx context.Context, client *client.Client, dn string, diags *diag.
...
 		path = fmt.Sprintf("/%s", path)
 	}
-
-	restRequest, err := client.MakeRestRequest(method, path, payload, true)
+	var restRequest *http.Request
+	var err error
+	if escapeHtml {
+		restRequest, err = client.MakeRestRequest(method, path, payload, true)
+	} else {
+		restRequest, err = client.MakeRestRequestRaw(method, path, payload.EncodeJSON(), true)
```
Comment (akinross) [inline internal/provider/utils.go:56]: How does this EncodeJson() function exactly work, because when I look at the function it mentions it does not escape by default but it can take a range of encoder options, like `EncodeOptHTMLEscape`. We never seem to pass in any options, would this function always set escaping to false?

File: internal/provider/utils.go [hunk 2]
```diff
@@ -41,14 +42,19 @@ func CheckDn(ctx context.Context, client *client.Client, dn string, diags *diag.
...
 	// Ensure path starts with a slash to assure signature is created correctly
 	if !strings.HasPrefix("/", path) {
 		path = fmt.Sprintf("/%s", path)
 	}
-
-	restRequest, err := client.MakeRestRequest(method, path, payload, true)
+	var restRequest *http.Request
+	var err error
+	if escapeHtml {
+		restRequest, err = client.MakeRestRequest(method, path, payload, true)
```
Comment (akinross) [inline internal/provider/utils.go:54]: So for the `standard` resources the escaping is not an issue and we keep same rest request structure?

**Review by akinross — CHANGES_REQUESTED** [review]

File: internal/provider/utils.go (hunk 2 above)
Comment (anvitha-jain) [reply internal/provider/utils.go:54]: yes, that is right.

File: internal/provider/resource_aci_rest_managed.go [hunk 3]
```diff
@@ -149,6 +151,12 @@ func (r *AciRestManagedResource) Schema(ctx context.Context, req resource.Schema
 				Default:             stringdefault.StaticString(globalAnnotation),
 				MarkdownDescription: `The annotation of the ACI object.`,
 			},
+			"escape_html": schema.BoolAttribute{
```
[the remark this answers is not in the document]
Comment (samiib) [reply internal/provider/resource_aci_rest_managed.go:154]: I agree with Akini, some extra test cases would be good.

**Review by samiib — CHANGES_REQUESTED** [review]

File: examples/aci_rest_managed/rest_managed.tf [hunk 4]
```diff
@@ -36,4 +36,19 @@ resource "aci_rest_managed" "fvTenant2" {
       annotation = "orchestrator:child"
     }
   }
+}
+
+resource "aci_rest_managed" "aaaPreLoginBanner" {
+  dn          = "uni/userext/preloginbanner"
+  class_name  = "aaaPreLoginBanner"
+  escape_html = false
```
[the remark this answers is not in the document]
Comment (anvitha-jain) [reply examples/aci_rest_managed/rest_managed.tf:44]: added.

File: internal/provider/utils.go [hunk 5]
```diff
@@ -41,14 +42,19 @@ func CheckDn(ctx context.Context, client *client.Client, dn string, diags *diag.
 	}
 }
 
-func DoRestRequest(ctx context.Context, diags *diag.Diagnostics, client *client.Client, path, method string, payload *container.Container) *container.Container {
+func DoRestRequest(ctx context.Context, diags *diag.Diagnostics, client *client.Client, path, method string, payload *container.Container, escapeHtml bool) *container.Container {
```
[the remark this answers is not in the document]
Comment (anvitha-jain) [reply internal/provider/utils.go]: Made these changes

File: internal/provider/resource_aci_rest_managed.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (anvitha-jain) [reply internal/provider/resource_aci_rest_managed.go:154]: yes. Added

File: internal/provider/utils.go (hunk 1 above)
Comment (anvitha-jain) [reply internal/provider/utils.go:56]: EncodeJson() avoids calling the string() function which internally calls unmarshall() (it again converts unique characters to unicode)

File: docs/data-sources/rest_managed.md [hunk 6]
```diff
@@ -33,7 +33,8 @@ data "aci_rest_managed" "example" {
 * `class_name` - (string) Which class object is being created.
 * `id` - (string) The Distinguished Name of the object.
 * `annotation` - (string) Annotation for the class object that is being created. When annotation is provided in content this will take precedence.
-* `content` (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
+* `content` - (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
+* `escape_html` - (Boolean) Enable escaping of HTML characters when encoding the JSON payload.
```
Comment (akinross) [inline docs/data-sources/rest_managed.md:37]: Do we need to expose this for the datasource, since we are only doing a get request to dn if not mistaken?

**Review by akinross — CHANGES_REQUESTED** [review]

File: docs/data-sources/rest_managed.md (hunk 6 above)
Comment (anvitha-jain) [reply docs/data-sources/rest_managed.md]: Removed from datasource

**Review by akinross — DISMISSED** [review]
LGTM

**Review by gmicol — DISMISSED** [review]
LGTM

File: docs/data-sources/rest_managed.md [hunk 7]
```diff
@@ -33,7 +33,7 @@ data "aci_rest_managed" "example" {
 * `class_name` - (string) Which class object is being created.
 * `id` - (string) The Distinguished Name of the object.
 * `annotation` - (string) Annotation for the class object that is being created. When annotation is provided in content this will take precedence.
-* `content` (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
+* `content` - (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
```
Comment (shrsr) [inline docs/data-sources/rest_managed.md:36]: -> A map of key-value pairs needs to be passed to the Model object as parameters. Make sure the key name matches the name of the ACI object.

File: docs/resources/rest_managed.md [hunk 8]
```diff
@@ -81,10 +81,13 @@ resource "aci_rest_managed" "example_tenant_with_child" {
 
 * `annotation` - (string) Annotation for the class object that is being created.
   - Default: `orchestrator:terraform`
-* `content` (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
+* `content` - (map) Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
```
Comment (shrsr) [inline docs/resources/rest_managed.md:84]: -> A map of key-value pairs needs to be passed to the Model object as parameters. Make sure the key name matches the name of the ACI object.

File: docs/resources/rest_managed.md [hunk 9]
```diff
@@ -94,7 +97,7 @@ resource "aci_rest_managed" "example_tenant_with_child" {
 
   #### Optional ###
 
-  * `content` (map) Map of key-value pairs which represents the attributes for the child object. When annotation is provided in the content of the child it will take precedence over the annotation set at the parent level.
+  * `content` - (map) Map of key-value pairs which represents the attributes for the child object. When annotation is provided in the content of the child it will take precedence over the annotation set at the parent level.
```
Comment (shrsr) [inline docs/resources/rest_managed.md:100]: -> A map of key-value pairs represents the attributes of the child object. Annotation defined within the child's content take precedence over annotation set at the parent level.

File: internal/provider/resource_aci_rest_managed.go [hunk 10]
```diff
@@ -149,6 +151,12 @@ func (r *AciRestManagedResource) Schema(ctx context.Context, req resource.Schema
...
+				Optional:            true,
+				Computed:            true,
```
Comment (shrsr) [inline internal/provider/resource_aci_rest_managed.go:156]: I'm not sure if providing Computed: true is allowed or even makes sense here?
@lhercot @akinross your thoughts?

**Review by shrsr — CHANGES_REQUESTED** [review]

File: internal/provider/resource_aci_rest_managed.go (hunk 10 above)
Comment (shrsr) [reply internal/provider/resource_aci_rest_managed.go:156]: This might be a new behaviour in the framework but in SDKv2 https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors the description is different.
Good to know!!

File: docs/resources/rest_managed.md (hunk 9 above)
Comment (anvitha-jain) [reply docs/resources/rest_managed.md]: fixed

File: docs/resources/rest_managed.md (hunk 8 above)
Comment (anvitha-jain) [reply docs/resources/rest_managed.md:84]: fixed

File: docs/data-sources/rest_managed.md (hunk 7 above)
Comment (anvitha-jain) [reply docs/data-sources/rest_managed.md]: fixed

**Review by akinross — DISMISSED** [review]
LGTM

**Review by gmicol — APPROVED** [review]

File: docs/data-sources/rest_managed.md (hunk 7 above)
Comment (shrsr) [reply docs/data-sources/rest_managed.md]: It's not fixed yet. Can you please check again?

**Review by samiib — DISMISSED** [review]
LGTM

File: docs/data-sources/rest_managed.md (hunk 7 above)
Comment (anvitha-jain) [reply docs/data-sources/rest_managed.md]: resolved

**Review by samiib — APPROVED** [review]
LGTM

**Review by akinross — APPROVED** [review]
LGTM

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by lhercot — APPROVED** [review]
